feat: added support fro reset_to_default prop
appbaseio/reactivecore pull request #104
Opened 2021-06-28 15:05 UTC by mohdashraf010897

**Description**: 

- Added Support for `resetToDefault` prop.
- Components are reset to default values using the redux action, `clearValuesToDefault`.

[RS PR](https://github.com/appbaseio/reactivesearch/pull/1725)

[Feature Request PR](https://github.com/appbaseio/reactivesearch/issues/1722)

[Notio Card](https://www.notion.so/appbase/ReactiveSearch-SelectedFilters-reset-to-default-value-99d4a8a722f14947ab41c33a18ee5312)

[Loom Demo: `Latest` Implementation](https://www.loom.com/share/bc69be97442144dbb801251ce999aac3)

[Docs PR](https://github.com/appbaseio/Docs/pull/206)

2021-06-28 17:15 UTC, bietkul requested changes

2021-06-28 17:15 UTC, bietkul commented on src/actions/value.js
> +import XDate from 'xdate';
@mohdashraf010897 You can not use `xdate` in this package.

2021-06-28 17:15 UTC, bietkul commented on src/actions/value.js
> +import { componentTypes } from '../../lib/utils/constants';
Wrong import statements. Use relative paths everywhere.

2021-06-28 17:15 UTC, bietkul commented on src/actions/value.js
> +				const formatInputDate = (date) => {
@mohdashraf010897 We should not load the `xdate` here or in `SelectedFilters` component.
You can handle this case in `dateRange` component itself.

2021-06-29 03:09 UTC, mohdashraf010897 commented on src/actions/value.js
> +				const formatInputDate = (date) => {
🆗

2021-06-29 03:09 UTC, mohdashraf010897 commented on src/actions/value.js
> +import XDate from 'xdate';
🆗

2021-06-29 06:26 UTC, bietkul approved these changes

2021-06-29 06:26 UTC, merged