Fix: Source Value for object dataField
appbaseio/reactivecore pull request #34
Opened 2019-04-02 11:39 UTC by jyash97

https://codesandbox.io/s/y27y53k881

Check this demo, in this the source is `member` object.

If we put dataField as `source.object.key` the source would be `object` because of this [line](https://github.com/appbaseio/reactivecore/blob/master/src/utils/suggestions.js#L78).

So to fix this I am now extracting the source directly from suggestion using the `_id`.

Closes https://github.com/appbaseio/reactivesearch/issues/857

2019-04-02 12:51 UTC, metagrover requested changes
Please do this implementation directly using the params values instead of finding and attaching the correct values of _source via `getSourceValue`.

2019-04-02 12:51 UTC, metagrover commented on src/utils/suggestions.js
> +	const getSourceValue = (id) => {
This has a complexity of On^2 ~ given it will be called inside a loop of hits.

2019-04-02 12:51 UTC, metagrover commented on src/utils/suggestions.js
> +	const parseField = (source, field, id) => {
Please refer the source from here instead of creating a getSourceValue function?

2019-04-02 12:51 UTC, metagrover commented on src/utils/suggestions.js
> +					...getSourceValue(_id),
Please do not use `getSourceValue` function here ~ On^2.

2019-04-09 07:28 UTC, lakhansamani approved these changes

2019-04-12 10:49 UTC, jyash97 commented
@bietkul If this looks good we can merge this, it will close two issues on RS

2019-04-15 22:48 UTC, bietkul approved these changes

2019-04-15 22:48 UTC, merged