fix: defaultQuery getting called with undefined values
appbaseio/reactivecore pull request #73
Opened 2020-04-20 10:58 UTC by ShahAnuj2610

2020-04-23 17:10 UTC, bietkul requested changes

2020-04-23 17:10 UTC, bietkul commented on src/utils/helper.js
> +			const { query, ...options } = evaluateQuery([], props);
@ShahAnuj2610 Why the value is an empty array?
Use the `current value` which is specific to the component.

2020-04-23 17:10 UTC, bietkul commented on src/utils/helper.js
>  		const evaluateQuery = defaultQuery();
@ShahAnuj2610 Make the code readable, it's hard to understand how you're passing `defaultQuery`.

2020-04-27 05:02 UTC, bietkul commented
@ShahAnuj2610 Any update here?

2020-04-27 05:29 UTC, ShahAnuj2610 commented
> @ShahAnuj2610 Any update here?

@bietkul fixing it today and updating the related PR.

2020-04-27 07:43 UTC, ShahAnuj2610 commented
@bietkul have uploaded test video for this and it's related PR

2020-05-07 12:45 UTC, bietkul approved these changes

2020-05-07 13:00 UTC, merged