fix: add support for more diacritics
appbaseio/reactivecore pull request #94
Opened 2021-04-22 08:51 UTC by lakhansamani

2021-05-27 15:25 UTC, siddharthlatest requested changes
This lgtm (y)

@lakhansamani The lint changes are inconsistent with the project's lint settings. Can we remove them?

2021-06-22 09:38 UTC, bietkul requested changes

2021-06-22 09:38 UTC, bietkul commented on src/utils/suggestions.js
> +	const diacritics = {
@lakhansamani This file is getting larger because of this constant. Please move it to a different file.

2021-06-25 08:33 UTC, lakhansamani commented
Fixed here https://github.com/appbaseio/reactivecore/pull/103

2021-06-25 08:33 UTC, closed without merging